### PR TITLE
Update actions to latest versions

### PR DESCRIPTION
**Pull request by irperkin**
Updated actions:
* [setup-node](https://github.com/marketplace/actions/setup-node-js-environment)
* [upload-artifact](https://github.com/marketplace/actions/upload-a-build-artifact#whats-new)
* [cache](https://github.com/marketplace/actions/cache)
* [setup-helm](https://github.com/marketplace/actions/helm-tool-installer)
* [setup-buildx-action](https://github.com/marketplace/actions/docker-setup-buildx)
* [docker-metadata-action](https://github.com/marketplace/actions/docker-metadata-action)
* [build-and-push-action](https://github.com/marketplace/actions/build-and-push-docker-images)

### CODE REVIEW

**Comment by irperkin** [comment]
A lot of these updates fix the set-output and node12 deprecation warnings. Inputs are pretty much all the same.

**Comment by mark-davenport-fountain** [comment]
I'll defer to @fountain-draloff and @polish-ambassador-ftn on this one. It's probably fine, but we don't have a great way to test other than to just send a release.

**Review by fountain-draloff — COMMENTED** [review]
LGTM, we'll test it out!

**Review by mark-davenport-fountain — APPROVED** [review]
🚢

**Pull request merged**
